<a href="https://colab.research.google.com/github/Ubaidl/Sentiment-Analysis-Using-LSTM/blob/main/sentiment_Analysis_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv('IMDB Dataset.csv',engine="python",encoding="utf-8",on_bad_lines="skip")

In [ ]:
data

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
8678  In Strangers On A Train, it's obvious from the...  positive
8679  The BBC'S Blue Planet is simply jaw-dropping. ...  positive
8680  I mistakenly kept myself awake late last night...  negative
8681  Its my favourite film because there's so much ...  positive
8682  As long as you go into this movie knowing that...  positive

[8683 rows x 2 columns]

In [ ]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
data.shape

(8683, 2)

In [ ]:
data['sentiment'].value_counts()

sentiment
positive    4359
negative    4324
Name: count, dtype: int64

In [ ]:
data.replace({"sentiment": {"positive": 1, "negative":0 }},inplace=True)

/tmp/ipython-input-631134849.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({"sentiment": {"positive": 1, "negative":0 }},inplace=True)


In [ ]:
data.head()

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding,LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
x_train_data, x_test_data=train_test_split(data,test_size=0.2,random_state=42)

In [ ]:
x_train_data

review  sentiment
8224  May Contain Spoilers!!! In no way, shape or fo...          1
437   This mostly routine fact-based TV drama gets a...          1
5452  "On a Clear Day You Can See Forever" is nothin...          0
8280  Things get dull early an often in this in this...          0
7643  Corky Romano has to be one of the most jaw dro...          0
...                                                 ...        ...
5734  Now don't get me wrong I love bad movies... no...          0
5191  How this film was made with so many big stars ...          0
5390  I can't knock this film too terribly, because ...          0
860   This production was quite a surprise for me. I...          1
7270  I was so excited to finally watch "Pulse" afte...          0

[6946 rows x 2 columns]

In [ ]:
x_train_data.shape

(6946, 2)

In [ ]:
tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(x_train_data['review'])


In [ ]:
sequences = tokenizer.texts_to_sequences(x_train_data['review'])

In [ ]:
padded_sequences = pad_sequences(sequences, maxlen=200)

In [ ]:
padded_sequences

array([[  16,   22,   31, ...,  140,    2,  140],
       [   0,    0,    0, ...,    3,   81,  103],
       [ 135,  145, 1615, ..., 2474,   72,   11],
       ...,
       [   0,    0,    0, ...,   40,    4,  159],
       [   0,    0,    0, ...,  240,  103,  120],
       [   7,  144,  650, ...,   23,   52,   57]], dtype=int32)

In [ ]:
x_train=pad_sequences( tokenizer.texts_to_sequences(x_train_data['review']),maxlen=200)

In [ ]:
x_test=pad_sequences( tokenizer.texts_to_sequences(x_test_data['review']),maxlen=200)

In [ ]:
x_train

array([[  16,   22,   31, ...,  140,    2,  140],
       [   0,    0,    0, ...,    3,   81,  103],
       [ 135,  145, 1615, ..., 2474,   72,   11],
       ...,
       [   0,    0,    0, ...,   40,    4,  159],
       [   0,    0,    0, ...,  240,  103,  120],
       [   7,  144,  650, ...,   23,   52,   57]], dtype=int32)

In [ ]:
x_test

array([[   0,    0,    0, ...,  540,   31, 4917],
       [   0,    0,    0, ..., 1210, 1210, 1210],
       [  34,  460,   15, ...,    6, 1342,  797],
       ...,
       [   0,    0,    0, ...,  130,   13, 1916],
       [   0,    0,    0, ...,   10,  361,  509],
       [   0,    0,    0, ...,   12,    9, 2557]], dtype=int32)

In [ ]:
y_train = x_train_data['sentiment']

In [ ]:
y_train

8224    1
437     1
5452    0
8280    0
7643    0
       ..
5734    0
5191    0
5390    0
860     1
7270    0
Name: sentiment, Length: 6946, dtype: int64

In [ ]:
y_test = x_test_data['sentiment']

In [ ]:
y_test

304     1
212     0
1793    1
1438    1
868     0
       ..
6726    1
2580    1
6299    1
8163    1
500     0
Name: sentiment, Length: 1737, dtype: int64

In [ ]:
model= Sequential()

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=5000, output_dim=128, input_length=200))
model.add(LSTM(128, dropout=0.2))
model.add(Dense(1, activation='sigmoid'))





/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer = "adam", loss= "binary_crossentropy", metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
218/218 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.6326 - loss: 0.6176
Epoch 2/5
218/218 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8634 - loss: 0.3405
Epoch 3/5
218/218 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.9051 - loss: 0.2421
Epoch 4/5
218/218 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9382 - loss: 0.1722
Epoch 5/5
218/218 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9557 - loss: 0.1322


In [ ]:
model.save("model.h5")

In [ ]:
import joblib
joblib.dump(tokenizer,"tokenizer.pkl")

['tokenizer.pkl']

In [ ]:
loss ,accuracy= model.evaluate(x_test, y_test)


55/55 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8464 - loss: 0.4734


In [ ]:
print(loss)

0.4658309817314148


In [ ]:
print(accuracy)

0.8503166437149048


In [ ]:
#Building predicting system


In [ ]:
def predictive_system(review):
  sequences = tokenizer.texts_to_sequences([review])
  padded_sequences = pad_sequences(sequences,maxlen=200)
  predictions = model.predict(padded_sequences)
  sentment = "positive" if predictions[0][0]>0.5 else "negative"
  return sentment


In [ ]:
predictive_system("The acting was awful and the plot made no sense.")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


'negative'